### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by wercsrsr** [nusdbsystem/pivot#1]
![image](https://user-images.githubusercontent.com/48711128/140636566-f8f2caa2-7d92-4001-804f-65d5d168f69f.png)
I can't find this file, nor can the program, which leads to a segment fault.

I tried to patch the file, but unfortunately, perhaps because of formatting issues, it didn't get any better.

**Comment by lemonviv** [comment]
Hi, thanks for your interest in this work. Commit 0f652e2cc91e5d41ab2e568bf2b7aa2b14dc3dc5 shall give an example of the network file. You could edit it if using a different party number or on different machines.

**Comment by wercsrsr** [comment]
Thanks very much ! 
It worked !
