### ISSUE TITLE
"client.host_names" segment fault

### ISSUE THREAD

**Issue by wercsrsr** [nusdbsystem/pivot#2]
https://github.com/nusdbsystem/pivot/blob/master/src/models/cart_tree.cpp#L306   When the program runs at this point, a segment error occurs.

I try to cout "client.host_names", however, an error occurs when the cout statement is compiled.
![image](https://user-images.githubusercontent.com/48711128/140708139-abee9494-6344-4351-a300-5f7d567189d5.png)
![image](https://user-images.githubusercontent.com/48711128/140708197-87f2da8c-c61c-42a1-af0b-9b644d3573e4.png)

**Comment by lemonviv** [comment]
The `setup_sockets` function is to set up communications with the MPC parties, you may need to check your `Pivot_SPDZ` parties are started and are listening on the correct ports, following the configurations [here](https://github.com/nusdbsystem/pivot#configuration).

The `cout` line you add is incorrect as `vector` cannot be printed directly in `c++`. Try to print using the `for` loop.
