### ISSUE TITLE
protobuf version mismatch

### ISSUE THREAD

**Issue by Sunflowerbeaut** [nusdbsystem/pivot#3]
I have installed protobuf 3.14.0 in my server according to README.md
![image](https://user-images.githubusercontent.com/106635456/171303697-2091cafc-54aa-4c6f-b5cb-2bbfbd50b05d.png)
However, when I run “make” in the created folder “build”, the program throws an error. The results are as follows.
![image](https://user-images.githubusercontent.com/106635456/171303751-ecf5aecf-b12f-4d69-b631-e5858413cd56.png)
Is the version of protobuf in Pivot earlier than 3.14.0? I have searched for this error but cannot get a solution to solve this problem.

**Comment by lemonviv** [comment]
Hi, have you re-generated the protobuf messages using the *.proto files under `src/include/meta/` folder? If you are building from source, you need to follow the steps in `tools/docker/Dockerfile` to install the dependencies and generate protobuf messages before making the project.

It is easier to build a docker image to run the tests using `tools/docker/Dockerfile`, or you can directly pull the docker image from `DockerHub` using `docker pull lemonwyc/pivot:latest`.
