### ISSUE TITLE
Error when running `./semi-party.x -F -N 3 -I -p 0 vfl_decision_tree`

### ISSUE THREAD

**Issue by Martinn1996** [nusdbsystem/pivot#4]
When I run `./semi-party.x -F -N 3 -I -p 0 vfl_decision_tree` in Docker, I get the following error: `qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction`. Any idea what's causing this?

**Comment by hhxxrhh** [comment]
I also have this problem. Is there any solution

**Comment by lemonviv** [comment]
If you can compile the program but failed to run it, you may check the machine's configuration and the OS you are using. Please refer to this issue https://github.com/data61/MP-SPDZ/issues/136 under MP-SPDZ for more information.

**Comment by hhxxrhh** [comment]
邮件已收到

**Comment by hhxxrhh** [comment]
邮件已收到
