### ISSUE TITLE
Can you update the code of spdz_util.cpp and spdz_util.h to better fit the latest SPDZ version?

### ISSUE THREAD

**Issue by shazi4399** [nusdbsystem/pivot#5]
I noticed that the version of SPDZ in Pivot-SPDZ is older and there are some template class and template function changes in the latest SPDZ framework.

1. the [send_private_inputs (older) ](https://github.com/nusdbsystem/pivot/blob/7c68babd5110191b328bed7f13e00dc13b722407/src/utils/spdz/spdz_util.cpp#L89) function has changed a lot.  Please  reference to  new [send_private_inputs (newer) ](https://github.com/data61/MP-SPDZ/blob/24c271b6a4f08d2f2db8ea2d40397f94dff51f31/ExternalIO/Client.hpp#L43) .
2. the Math/gfp.h and Math/gfp.cpp files became Math/gfp.h and Math/gfp.hpp files. Please reference to [gfp.hpp](https://github.com/data61/MP-SPDZ/blob/master/Math/gfp.hpp)

I would like to replace some of the original parts of pivot with the new SPDZ function, but find it difficult to do so.
Can you provide me some help or advices?

**Comment by lemonviv** [comment]
Yes, Pivot-SPDZ is built on top of commit [2c3606c](https://github.com/data61/MP-SPDZ/commit/2c3606ccb2658cea10826d670298e04b1385415a) of MP-SPDZ. For the [Client](https://github.com/data61/MP-SPDZ/blob/24c271b6a4f08d2f2db8ea2d40397f94dff51f31/ExternalIO/Client.hpp) example, they modified the previous example with functions to a Client class, the invocation API is changed slightly by assigning the sockets when initializing a Client instance, the rest of the implementation is similar. 

If you would like to integrate with the latest SPDZ version, you may try to run an MPC program with its ExternalIO example first, and then add the invocation method to pivot spdz_util. We used a [newer version of SPDZ](https://github.com/data61/MP-SPDZ/commit/72c2d4b3f73fff93c4d7c2cc58bc6e146eaf3a9b) but not the latest in an upgraded system [falcon](https://github.com/nusdbsystem/falcon), you may refer to it to see if it helps.
